### ISSUE TITLE
"Can't connect to server" with TCPShield plugin installed on Velocity.

### ISSUE THREAD

**Issue by ghost** [TCPShield/RealIP#63]
I configured everything correctly and installed the TCPShield plugin on Velocity, but my server cannot be found on the domain I was setting up. This problem is relevant only for Velocity, I checked it work on Spigot and BungeeCord and everything seems to work fine. But I need to use Velocity, since my main server is built on Fabric, and the TCPShield plugin does not work on it. And only Velocity can work normally with modified Fabric servers.

**Comment by MAXOUXAX** [comment]
Most likely linked to #54 
You can temporarly set `only-allow-proxy-connections` to false if you want to be able to connect to your Proxy (see https://github.com/TCPShield/RealIP/issues/54#issuecomment-857495590)

**Comment by trev-sharp** [comment]
Make sure you are using the latest build of TCPShield and using at least Java 11 (_Follow The Instructions On How To Build With Gradle_) then try it again. If no errors are present, open a support ticket on the discord, but if there are errors present, send them here so we can further assist. This issue could be linked to [issue #54](https://github.com/TCPShield/RealIP/issues/54), but this issue was fully resolved with the lastest build, as mentioned by [my comment](https://github.com/TCPShield/RealIP/issues/54#issuecomment-878260883)

**Comment by MAXOUXAX** [comment]
> Make sure you are using the latest build of TCPShield and using at least Java 11 (_Follow The Instructions On How To Build With Gradle_) then try it again. If no errors are present, open a support ticket on the discord, but if there are errors present, send them here so we can further assist. This issue could be linked to [issue #54](https://github.com/TCPShield/RealIP/issues/54), but this issue was fully resolved with the lastest build, as mentioned by [my comment](https://github.com/TCPShield/RealIP/issues/54#issuecomment-878260883)

I cloned the repo and tried to build the project, but Gradle is giving me this error.

```java
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processResources'.
> Entry bungee.yml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

Do you have any JAR for us to test?

**Comment by ghost** [comment]
> Make sure you are using the latest build of TCPShield and using at least Java 11 (_Follow The Instructions On How To Build With Gradle_) then try it again. If no errors are present, open a support ticket on the discord, but if there are errors present, send them here so we can further assist. This issue could be linked to [issue #54](https://github.com/TCPShield/RealIP/issues/54), but this issue was fully resolved with the lastest build, as mentioned by [my comment](https://github.com/TCPShield/RealIP/issues/54#issuecomment-878260883)

where is latest build?
if you mean v2.5, then this issue is not resolved on this version

**Comment by trev-sharp** [comment]
> > Make sure you are using the latest build of TCPShield and using at least Java 11 (_Follow The Instructions On How To Build With Gradle_) then try it again. If no errors are present, open a support ticket on the discord, but if there are errors present, send them here so we can further assist. This issue could be linked to [issue #54](https://github.com/TCPShield/RealIP/issues/54), but this issue was fully resolved with the lastest build, as mentioned by [my comment](https://github.com/TCPShield/RealIP/issues/54#issuecomment-878260883)
> 
> 
> 
> where is latest build?
> 
> if you mean v2.5, then this issue is not resolved on this version

You will need to build the current GitHub repository with Gradle (_Follow the instructions in the README_) The v2.5 _release_ is a few commits behind the latest code; we have since fixed a handle of bugs.

**Comment by ghost** [comment]
> > > Make sure you are using the latest build of TCPShield and using at least Java 11 (_Follow The Instructions On How To Build With Gradle_) then try it again. If no errors are present, open a support ticket on the discord, but if there are errors present, send them here so we can further assist. This issue could be linked to [issue #54](https://github.com/TCPShield/RealIP/issues/54), but this issue was fully resolved with the lastest build, as mentioned by [my comment](https://github.com/TCPShield/RealIP/issues/54#issuecomment-878260883)
> > 
> > 
> > where is latest build?
> > if you mean v2.5, then this issue is not resolved on this version
> 
> You will need to build the current GitHub repository with Gradle (_Follow the instructions in the README_) The v2.5 _release_ is a few commits behind the latest code; we have since fixed a handle of bugs.

i build it from sources and this still doesn't working

**Comment by viper12358** [comment]
> where is latest build?

Try using this one:
https://drive.google.com/file/d/113s01ZlT-d9oCJnpOcgboSF4eJAw4CNd/view?usp=sharing
 
>> i build it from sources and this still doesn't working

And make sure that you are using AdoptOpenJDK (do java -version to check). That's the only discrepancy that we've found with one of our customer who also have this problem.

I have personally tested Velocity 1.8.8 and above (upto 3.0.0) with Paper, Yatopia and they works fine.

**Comment by GitReboot** [comment]
> > Make sure you are using the latest build of TCPShield and using at least Java 11 (_Follow The Instructions On How To Build With Gradle_) then try it again. If no errors are present, open a support ticket on the discord, but if there are errors present, send them here so we can further assist. This issue could be linked to [issue #54](https://github.com/TCPShield/RealIP/issues/54), but this issue was fully resolved with the lastest build, as mentioned by [my comment](https://github.com/TCPShield/RealIP/issues/54#issuecomment-878260883)
> 
> I cloned the repo and tried to build the project, but Gradle is giving me this error.
> 
> ```java
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':processResources'.
> > Entry bungee.yml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
> ```
> 
> Do you have any JAR for us to test?

I am having the same issue. Any solution?

**Comment by GitReboot** [comment]
> > > Make sure you are using the latest build of TCPShield and using at least Java 11 (_Follow The Instructions On How To Build With Gradle_) then try it again. If no errors are present, open a support ticket on the discord, but if there are errors present, send them here so we can further assist. This issue could be linked to [issue #54](https://github.com/TCPShield/RealIP/issues/54), but this issue was fully resolved with the lastest build, as mentioned by [my comment](https://github.com/TCPShield/RealIP/issues/54#issuecomment-878260883)
> > 
> > 
> > I cloned the repo and tried to build the project, but Gradle is giving me this error.
> > ```java
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':processResources'.
> > > Entry bungee.yml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you have any JAR for us to test?
> 
> I am having the same issue. Any solution?

Nevermind. Just had to add this to build.gradle
processResources {
    duplicatesStrategy = 'exclude'
    }
}

**Comment by DylanKeir** [comment]
If this is still an issue, please create a ticket at https://discord.gg/tcpshield and we'll help you through fixing it.
